name = "attendance-management-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# D1データベース設定（開発環境用）
[[d1_databases]]
binding = "DB"
database_name = "attendance_db_dev"
database_id = "50cf79fb-7923-4db7-bc3e-7beda4d42509"
migrations_dir = "src/db/migrations"

# 環境変数
[vars]
ENVIRONMENT = "development"

# 開発環境設定
[env.development]
# ローカル開発用のD1データベース設定
# [[env.development.d1_databases]]
# binding = "DB" 
# database_name = "attendance_db_dev"
# database_id = "development-db-id"
# preview_database_id = "development-preview-id"

# 本番環境設定
[env.production]
vars = { ENVIRONMENT = "production" }
[[env.production.d1_databases]]
binding = "DB"
database_name = "attendance_db_prod"
database_id = "ac461ea1-bcf9-4128-b6b1-30fc08573f2d"

# ビルド設定
[build]
command = "npm run build" 